# program for collecting bio data
print('Welcome to the bio data collector!')
name = input('Enter your name: ')
age = int(input('Enter your age: '))
course = input('Enter your course: ')
address = input('Enter your address: ')
married = bool(input('Is married? [True / false]: '))
nationality = input('Enter your nationality: ')
postal_code = int(input('Enter your postal_code: '))

print('/n')
print('The given data are as follows: ')
print(name)
print(age)
print(course)
print(address)
print(married)
print(nationality)
print(postal_code)
