# Q) Program to read employee data from user and print the data.
print('Welcome to the bio data collector!')
name = input('Enter your name: ')
age = int(input('Enter your age: '))
course = input('Enter your course: ')
address = input('Enter your address: ')
married = bool(input('Is married? [True / false]: '))
nationality = input('Enter your nationality: ')
postal_code = int(input('Enter your postal_code: '))

print('/n')
print('The given data are as follows: ')
print('Name: ',name)
print('Age',age)
print('Course',course)
print('Address',address)
print('Married',married)
print('Nationality',nationality)
print('Postal_code',postal_code)
